### ISSUE TITLE
Enable opcache to run full list of PHPT tests in test package

### ISSUE THREAD

**Issue by hollyhuiLi** [php/pftt2#30]
When we manually run PHPT tests with run-test.php, we could update the php.ini to enable opcache to run the full set of tests. Switch to PFTT, we need to figure out the right way to run PHPT tests with opcache on:
There is an opcache.groovy enables opcache scenario, but it seems only good for tests under ext/opcache ( more failures testing other tests)
Also, add opcache.groovy together with default.groovy like below will cause the pftt tool to run tests twice
pftt -config opcache,default core_list ...
Adding a new groovy to return combination of opcache and default scenarios will also run the tests twice

**Comment by cmb69** [comment]
It seems to me that running with `-config opcache` works as intended, i.e. the tests are executed with Opcache enabled. Test failures when running parallel tests with Opcache enabled are not unlikely to occur on Windows; see php/php-src#3851. There's a preliminary fix to allow to have [multiple Opcache instances](https://github.com/cmb69/php-src/tree/opcache.cache_id), which needs more testing (I'll do that ASAP). Then this has to be supported by PFTT2, and also PFTT2 needs to support [--CONFLICTS--](http://qa.php.net/phpt_details.php#conflicts_section). The PHPTs in PHP-7.3 and earlier do not have --CONFLICTS-- clauses, so for these versions PFTT must not run parallel tests when Opcache is enabled, even when the mentioned improvements are in place.

I wonder, though, how PFTT2 currently handles the missing --CONFLICTS-- clauses; these are actually not particularly related to Opcache, but rather deal with the fact that the PHPTs have originally not supposed to be run in parallel.

**Comment by hollyhuiLi** [comment]
If I understood correctly, the more failed tests under PFTT2 with -config opcache are as expected because of they are running in parallel? But we didn't see that much of failure when we run PHPT tests with run-test.php, even we have multiple instances of cmd windows running for different builds. Is that because PFTT2 has more more threads and there are quite a lot of tests running in parallel which increased the chance of failing?

**Comment by cmb69** [comment]
@hollyhuiLi As it is now, there is a separate Opcache instance per user and [PHP version](https://github.com/php/php-src/blob/php-7.3.6RC1/ext/opcache/ZendAccelerator.c#L2632-L2657) (on Windows). That means different PHP builds will have their own Opcache instance, so there shouldn't be any issues (besides the general --CONFLICTS-- issue) running these test suites in parallel. Running tests for the same PHP build in parallel (multiple cmd windows) is likely to have issues. And for PFTT2 the situation is likely worse, due to the many parallel threads using the same Opcache instance.

**Comment by cmb69** [comment]
@lavturo, is this still an issue? It seems to me that `-config opcache` works as expected (potential test failures due to parallel running tests would be a different issue).

**Comment by lavturo** [comment]
@cmb69 If this is in regards to `-config opcache`, then it's fine. That is not an issue.

**Comment by cmb69** [comment]
Thanks for the confirmation. So this ticket can be closed.
