### ISSUE TITLE
[test issue] Time Zone not set correctly

### ISSUE THREAD

**Issue by hollyhuiLi** [php/pftt2#44]
test case: ext/date/tests/bug33532.phpt
diff:
&#64;&#64; -4,1 +4,1 &#64;&#64;
 Should strftime==datestr? Strftime seems to assume GMT tStamp.
 input    10:00:00 AM July 1 2005
+strftime 10:00:00 AM July 1 2005 Pacific Standard Time -0800
-strftime 10:00:00 AM July 1 2005 UTC +0000
&#64;&#64; -9,1 +9,1 &#64;&#64;
 
 Setting TZ
 input    10:00:00 AM July 1 2005
+strftime 10:00:00 AM July 1 2005 Pacific Standard Time -0800
-strftime 10:00:00 AM July 1 2005 AEST +1000
-datestr  10:00:00 AM July 1 2005 AEST

**Comment by cmb69** [comment]
Hmm, this test is supposed to be skipped on Windows: https://github.com/php/php-src/blob/e18c60cd8dfed02311ebb3d11e3543d9a99c7c2a/ext/date/tests/bug33532.phpt#L8

Maybe #41 isn't sufficient for proper `--SKIPIF--` support?

**Comment by hollyhuiLi** [comment]
Maybe, I did included #41 before I run the test with PFTT, I will double check tomorrow.

There are more tests related to SKIPIF not evaluated correctly, details in issue #47 and #48 .

**Comment by hollyhuiLi** [comment]
closed by #57
