### ISSUE TITLE
[test issue] [SKIPIF] 32 bit test not skipped on 64 bit PHP

### ISSUE THREAD

**Issue by hollyhuiLi** [php/pftt2#47]
when SKIPIF reference PHP_INT_SIZE, it may not work properly

34 test cases impacted:
ext/standard/tests/array/bug41121.phpt
ext/standard/tests/math/pow_basic.phpt
ext/standard/tests/network/ip2long_variation2.phpt
ext/standard/tests/strings/sscanf_basic6.phpt
ext/standard/tests/strings/vfprintf_basic7.phpt
ext/standard/tests/strings/vfprintf_variation11.phpt
ext/standard/tests/strings/vfprintf_variation12.phpt
ext/standard/tests/strings/vfprintf_variation13.phpt
ext/standard/tests/strings/vfprintf_variation14.phpt
ext/standard/tests/strings/vfprintf_variation15.phpt
ext/standard/tests/strings/vfprintf_variation16.phpt
ext/standard/tests/strings/vfprintf_variation19.phpt
ext/standard/tests/strings/vfprintf_variation4.phpt
ext/standard/tests/strings/vprintf_basic7.phpt
ext/standard/tests/strings/vprintf_variation11.phpt
ext/standard/tests/strings/vprintf_variation12.phpt
ext/standard/tests/strings/vprintf_variation13.phpt
ext/standard/tests/strings/vprintf_variation14.phpt
ext/standard/tests/strings/vprintf_variation15.phpt
ext/standard/tests/strings/vprintf_variation16.phpt
ext/standard/tests/strings/vprintf_variation19.phpt
ext/standard/tests/strings/vprintf_variation4.phpt
ext/standard/tests/strings/vsprintf_variation15.phpt
tests/lang/operators/operator_equals_variation.phpt
tests/lang/operators/operator_gt_or_equal_variation.phpt
tests/lang/operators/operator_identical_variation.phpt
tests/lang/operators/operator_lt_or_equal_variation.phpt
tests/lang/operators/operator_notequals_variation.phpt
tests/lang/operators/operator_notidentical_variation.phpt
zend/tests/binary-32bit.phpt
zend/tests/bug46701.phpt
zend/tests/bug70173.phpt
zend/tests/dval_to_lval_32.phpt
zend/tests/int_underflow_32bit.phpt

**Comment by hollyhuiLi** [comment]
9 more test cases:

ext/com_dotnet/tests/bug33386.phpt
ext/com_dotnet/tests/variants.phpt
ext/date/tests/mktime-3.phpt
ext/date/tests/strtotime-mysql.phpt
ext/date/tests/strtotime3.phpt
ext/mysqli/tests/036.phpt
ext/pdo_sqlite/tests/bug_63916-2.phpt
ext/sqlite3/tests/bug63921-32bit.phpt
tests/lang/constants/php_int_32bit.phpt

**Comment by cmb69** [comment]
Just to clarify: it is not relevant whether the OS is 64bit, but rather whether the PHP binary is compiled for x86 or x64. In the former case these tests are supposed to run (successfully).

**Comment by hollyhuiLi** [comment]
yes, changed the title.

**Comment by cmb69** [comment]
Closed with fbf6589a25163f8ea175a3820a9858a145f1995c.

**Comment by hollyhuiLi** [comment]
Closed
