### ISSUE TITLE
[test issue] Some not for windows tests are not skipped 

### ISSUE THREAD

**Issue by hollyhuiLi** [php/pftt2#48]
Variable reasons that SKIPIF not evaluated correctly.

26 test cases:

ext/openssl/tests/stream_server_reneg_limit.phpt
ext/phar/tests/bug77022.phpt
ext/session/tests/bug42596.phpt
ext/sqlite3/tests/sqlite3_15_open_error.phpt
ext/standard/tests/directory/directory_constants.phpt
ext/standard/tests/file/basename_basic.phpt
ext/standard/tests/file/basename_variation1.phpt
ext/standard/tests/file/basename_variation2.phpt
ext/standard/tests/file/bug39367.phpt
ext/standard/tests/file/chmod_basic.phpt
ext/standard/tests/file/chmod_variation1.phpt
ext/standard/tests/file/readfile_basic-win32.phpt
ext/standard/tests/file/windows_links/bug48746_3.phpt
ext/standard/tests/file/windows_links/bug73962.phpt
ext/standard/tests/general_functions/bug44295.phpt
ext/standard/tests/general_functions/escapeshellarg_basic.phpt
ext/standard/tests/general_functions/escapeshellarg_variation1.phpt
ext/standard/tests/mail/bug51604.phpt
ext/standard/tests/mail/bug73203.phpt
ext/standard/tests/mail/mail_basic.phpt
ext/standard/tests/mail/mail_basic3.phpt
ext/standard/tests/mail/mail_basic5.phpt
ext/standard/tests/mail/mail_variation1.phpt
ext/standard/tests/streams/stream_get_contents_002.phpt
ext/zlib/tests/gzencode_variation1.phpt
zend/tests/bug74093.phpt

**Comment by hollyhuiLi** [comment]
4 more tests:

ext/opcache/tests/issue0183.phpt
ext/standard/tests/file/readfile_basic.phpt
ext/standard/tests/network/bug64330.phpt
tests/security/open_basedir_001.phpt

**Comment by cmb69** [comment]
Closed with fbf6589a25163f8ea175a3820a9858a145f1995c.

**Comment by hollyhuiLi** [comment]
closed
