### ISSUE TITLE
[Test Issue] Uncaught Error on some pdo_mysql tests

### ISSUE THREAD

**Issue by hollyhuiLi** [php/pftt2#64]
16 pdo_mysql tests failed due to uncaught error

ext/pdo_mysql/tests/bug70862.phpt
ext/pdo_mysql/tests/bug_41698.phpt
ext/pdo_mysql/tests/pdo_mysql_attr_autocommit.phpt
ext/pdo_mysql/tests/pdo_mysql_attr_case.phpt
ext/pdo_mysql/tests/pdo_mysql_commit.phpt
ext/pdo_mysql/tests/pdo_mysql_errorcode.phpt
ext/pdo_mysql/tests/pdo_mysql_errorinfo.phpt
ext/pdo_mysql/tests/pdo_mysql_prepare_emulated_anonymous.phpt
ext/pdo_mysql/tests/pdo_mysql_prepare_native.phpt
ext/pdo_mysql/tests/pdo_mysql_prepare_native_placeholder_everywhere.phpt
ext/pdo_mysql/tests/pdo_mysql_rollback.phpt
ext/pdo_mysql/tests/pdo_mysql_stmt_bindparam_types.phpt
ext/pdo_mysql/tests/pdo_mysql_stmt_bindvalue.phpt
ext/pdo_mysql/tests/pdo_mysql_stmt_blobs.phpt
ext/pdo_mysql/tests/pdo_mysql_stmt_closecursor_empty.phpt
ext/pdo_mysql/tests/pdo_mysql_stmt_columncount.phpt

Example for ext/pdo_mysql/tests/bug70862.phpt:
&#64;&#64; -1,2 +1,9 &#64;&#64;
+PHP Fatal error:  Uncaught Error: Call to a member function bindParam() on bool in D:\php\testpackage\7.3.9RC1\ext\pdo_mysql\tests\bug70862.php:22
+Stack trace:
+#0 {main}
+  thrown in D:\php\testpackage\7.3.9RC1\ext\pdo_mysql\tests\bug70862.php on line 22
+
+Fatal error: Uncaught Error: Call to a member function bindParam() on bool in D:\php\testpackage\7.3.9RC1\ext\pdo_mysql\tests\bug70862.php:22
+Stack trace:
+#0 {main}
+  thrown in D:\php\testpackage\7.3.9RC1\ext\pdo_mysql\tests\bug70862.php on line 22
-string(0) ""
-done!
 #0 {main}
   thrown in D:\php\testpackage\7.3.9RC1\ext\pdo_mysql\tests\bug70862.php on line 22

**Comment by cmb69** [comment]
This *might* be a parallel testing issue, see #61.

**Comment by hollyhuiLi** [comment]
Verified that it is similar issue as #61. Actually the change fixed #61 also added pdo_mysql test as non-threadsafe, and fixed this bug as well.
