### ISSUE TITLE
PHP Deprecated causes failures

### ISSUE THREAD

**Issue by hollyhuiLi** [php/pftt2#67]
For deprecated functions, both message and behavior are different 

Related test cases:
ext/mbstring/tests/bug52931.phpt
ext/opcache/tests/bug68644.phpt
ext/opcache/tests/bug75729.phpt
zend/tests/bug47320.phpt

Example diff for ext/mbstring/tests/bug52931.phpt
&#64;&#64; -1,5 +1,1 &#64;&#64;
+PHP Deprecated:  The mbstring.func_overload directive is deprecated in Unknown on line 0
-Deprecated: The mbstring.func_overload directive is deprecated in Unknown on line 0
-int(27)
-int(27)
-int(20)
-int(20)

**Comment by cmb69** [comment]
Apparently, your INI settings are `display_errors=0` (which suppresses the expected message) and `log_errors=1` (which triggers the message you've got). I wonder why [`error_log` defaults to on](https://github.com/php/pftt2/blob/1354c8c0f18ed9a49f3fd353d8a6f823131ea7b6/src/com/mostc/pftt/model/smoke/RequiredExtensionsSmokeTest.java#L237); might be something that we want to change. Anyhow, you have to fix your php.ini accordingly.

**Comment by cmb69** [comment]
Since this is just about a PHP INI setting, I'm closing this ticket. Thanks.

**Comment by cmb69** [comment]
Well, actually this is a bug in PFTT, since it uses wrong defaults for these INI settings.
